// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSMgwh6MNaIt_V__Jr7kbsI6lYInvvNWU',
    appId: '1:852661976409:web:5ba97d1f023a3666b9e048',
    messagingSenderId: '852661976409',
    projectId: 'flashmind-1538',
    authDomain: 'flashmind-1538.firebaseapp.com',
    storageBucket: 'flashmind-1538.firebasestorage.app',
    measurementId: 'G-REXTXY3S3J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNKskSGJ_q9F7vEniIAOVE2gVn-SVCJGQ',
    appId: '1:852661976409:android:d694436cdd3b83aab9e048',
    messagingSenderId: '852661976409',
    projectId: 'flashmind-1538',
    storageBucket: 'flashmind-1538.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ7HnA5jbxfYTN4t1AAJL0XPMUsvkaMV4',
    appId: '1:852661976409:ios:83b8f504632281c7b9e048',
    messagingSenderId: '852661976409',
    projectId: 'flashmind-1538',
    storageBucket: 'flashmind-1538.firebasestorage.app',
    iosClientId: '852661976409-vc6j8lfp88b9er3tmaq2fah3ht3jc24s.apps.googleusercontent.com',
    iosBundleId: 'com.example.learning',
  );
}
